import { Destination } from "@/types";

export const destinations: Destination[] = [
  {
    id: 1,
    name: "Paris",
    country: "France",
    image:
      "https://plus.unsplash.com/premium_photo-1661919210043-fd847a58522d?q=80&w=2942&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "The city of love!",
    population: "2.1M",
    bestTimeToVisit: "April - June, September - November",
    attractions: ["Eiffel Tower", "Louvre Museum", "Notre Dame"],
    currency: "Euro (€)",
    language: "French",
  },
  {
    id: 2,
    name: "Tokyo",
    country: "Japan",
    image:
      "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?q=80&w=2988&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "A mix of tradition and technology.",
    population: "14M",
    bestTimeToVisit: "March - May, September - November",
    attractions: ["Shibuya Crossing", "Tokyo Tower", "Meiji Shrine"],
    currency: "Japanese Yen (¥)",
    language: "Japanese",
  },
  {
    id: 3,
    name: "New York",
    country: "USA",
    image:
      "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "The city that never sleeps.",
    population: "8.5M",
    bestTimeToVisit: "April - June, September - November",
    attractions: ["Statue of Liberty", "Times Square", "Central Park"],
    currency: "US Dollar ($)",
    language: "English",
  },
  {
    id: 4,
    name: "Barcelona",
    country: "Spain",
    image:
      "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "The city of Gaudí.",
    population: "1.6M",
    bestTimeToVisit: "April - June, September - October",
    attractions: ["Sagrada Familia", "Park Güell", "La Rambla"],
    currency: "Euro (€)",
    language: "Spanish, Catalan",
  },
  {
    id: 5,
    name: "Cape Town",
    country: "South Africa",
    image:
      "https://plus.unsplash.com/premium_photo-1697730061063-ad499e343f26?q=80&w=2832&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "The city of the Table Mountain.",
    population: "4.7M",
    bestTimeToVisit: "November - March",
    attractions: ["Table Mountain", "Robben Island", "Cape Point"],
    currency: "South African Rand (ZAR)",
    language: "English, Afrikaans",
  },
  {
    id: 6,
    name: "Sydney",
    country: "Australia",
    image:
      "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "The city of the Opera House.",
    population: "5.3M",
    bestTimeToVisit: "September - November, March - May",
    attractions: ["Sydney Opera House", "Bondi Beach", "Harbour Bridge"],
    currency: "Australian Dollar (AUD)",
    language: "English",
  },
  {
    id: 7,
    name: "Rio de Janeiro",
    country: "Brazil",
    image:
      "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "The city of Christ the Redeemer.",
    population: "6.7M",
    bestTimeToVisit: "December - March",
    attractions: [
      "Christ the Redeemer",
      "Copacabana Beach",
      "Sugarloaf Mountain",
    ],
    currency: "Brazilian Real (BRL)",
    language: "Portuguese",
  },
  {
    id: 8,
    name: "Marrakech",
    country: "Morocco",
    image:
      "https://images.unsplash.com/photo-1597212618440-806262de4f6b?q=80&w=2946&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "The city of the souks.",
    population: "928K",
    bestTimeToVisit: "March - May, September - November",
    attractions: ["Jemaa el-Fnaa", "Majorelle Garden", "Medina"],
    currency: "Moroccan Dirham (MAD)",
    language: "Arabic, French",
  },
  {
    id: 9,
    name: "Dubai",
    country: "United Arab Emirates",
    image:
      "https://plus.unsplash.com/premium_photo-1661943659036-aa040d92ee64?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "The city of the Burj Khalifa.",
    population: "3.5M",
    bestTimeToVisit: "November - April",
    attractions: ["Burj Khalifa", "Dubai Mall", "Palm Jumeirah"],
    currency: "UAE Dirham (AED)",
    language: "Arabic, English",
  },
  {
    id: 10,
    name: "Bali",
    country: "Indonesia",
    image:
      "https://images.unsplash.com/photo-1555400038-63f5ba517a47?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "The city of temples.",
    population: "4.3M",
    bestTimeToVisit: "April - October",
    attractions: [
      "Uluwatu Temple",
      "Tegallalang Rice Terraces",
      "Seminyak Beach",
    ],
    currency: "Indonesian Rupiah (IDR)",
    language: "Indonesian, Balinese",
  },
];
